---
- name: Check if system is registered to Satellite
  ansible.builtin.shell: subscription-manager status | grep 'Overall Status' | awk '{print $3}'
  register: subscription_status_check
  changed_when: false
  tags: [registration_check]


---
- name: Check if system has a Satellite identity
  ansible.builtin.shell: subscription-manager identity
  register: system_identity_check
  failed_when: false
  changed_when: false
  tags: [registration_check]