#SPDX-License-Identifier: MIT-0
---
# defaults file for aap_cve_patch
# Control flags
run_pre_checks: true
enable_satellite_registration_check: true
enable_repo_check: true
enable_errata_reporting: true

# Patch toggles
apply_security_patches: true
apply_bugfix_patches: false
apply_enhancement_patches: false
apply_kernel_patches: true

# Safety
fail_if_not_registered: true
fail_if_repo_missing: true