---
- name: uri module test
  hosts: localhost
  become: false

  tasks:
    - name: Get ping
      ansible.builtin.uri:
        url: "http://localhost/api/v2/ping/"
        method: GET
        status_code: 200
        timeout: 30
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result
