---
- name: MONITORING_process_audit role execution
  hosts: all
  gather_facts: true
  become: yes
  roles:
    - audit_processes

- name: Build single consolidated audit report (ALL HOSTS)
  hosts: localhost
  gather_facts: no
  run_once: true

  tasks:
    - name: Build consolidated report as single variable
      set_fact:
        consolidated_audit_report: |
          Process Execution Audit – Consolidated Report
          =============================================
          Date: {{ lookup('pipe', 'date +%F') }}

          {% for host in groups['all'] %}
          Host: {{ host }}
          -----------------------------
          Commands executed yesterday: {{ hostvars[host].process_exec_host_report.yesterday_count }}
          Commands executed today: {{ hostvars[host].process_exec_host_report.today_count }}

          Newly executed commands today:
          {% if hostvars[host].process_exec_host_report.new_commands | length > 0 %}
          {% for cmd in hostvars[host].process_exec_host_report.new_commands %}
          - {{ cmd }}
          {% endfor %}
          {% else %}
          No changes detected
          {% endif %}

          {% endfor %}
