---
- name: Check service status
  hosts: all
  become: yes
  become_user: root
  tasks:
      - name: Check nginx service
        service:
            name=nginx
            state=started
            enabled=yes

- hosts: all
  gather_facts: no
  tasks:
    - action: ping

- name: Install package tree
  yum:
      name: "{{ item }}"
      state: present
  loop:
      - tree
      - nmap
        
- name: Erase installed package.
  yum:
    name: tree
    state: absent
