---
- name: Hello World Sample
  hosts: all
  become: yes
  become_user: root
  tasks:
      - name: Check httpd service
        service:
            name=httpd
            state=started
            enabled=yes
