---
- name: Check service status
  hosts: all
  become: yes
  become_user: root
  tasks:
      - name: Check sshd service
        service:
            name=nginx
            state=started
            enabled=yes
