---
- name: Hello World Sample
  hosts: all
  become: yes
  become_user: root
  tasks:
      - name: Check sshd service
        service:
            name=sshd
            state=started
            enabled=yes
