# SPDX-License-Identifier: MIT-0
---
- name: Run DEIO Backup
  hosts: all
  gather_facts: false
  roles:
    - deio_backup_new

#- name: Send DEIO Backup Report
#  hosts: localhost
#  gather_facts: false
#  tasks:
#    - name: Render consolidated report
#      ansible.builtin.template:
#        src: "roles/deio_backup/templates/deio_backup_report.j2"
#        dest: "{{ report_file }}"
#
#    - name: Send report via email
#      ansible.builtin.mail:
#        host: "{{ smtp_host }}"
#        port: "{{ smtp_port }}"
#        to: "{{ report_email_to }}"
#        from: "{{ report_email_from }}"
#        subject: "{{ report_email_subject }}"
#        body: "{{ lookup('file', report_file) }}"

---
- name: Run DEIO Backup and Email Summary
  hosts: all
  gather_facts: false
  roles:
    - deio_backup

  tasks:
    # Consolidate and email results
    - name: Gather all backup results
      ansible.builtin.set_fact:
        all_backup_results: "{{ hostvars | dict2items | map(attribute='value.deio_backup_result') | select('defined') | list }}"
      run_once: true

    - name: Build combined email body
      ansible.builtin.set_fact:
        deio_email_body: |
          Hello Team,

          Here’s the consolidated DEIO Backup Summary for {{ all_backup_results[0].today_date }}:

          {% for result in all_backup_results %}
          ------------------------------------------------------------------
          🔹 Server: {{ result.hostname }}
          🔸 Day: {{ result.day }}
          🔸 Backup Performed: {{ (not result.backup_skipped) | ternary('Yes', 'No (Skipped)') }}
          🔸 Startup Performed: {{ (not result.startup_skipped) | ternary('Yes', 'No (Skipped)') }}
          🔸 Backup Directory: {{ result.backup_dir }}
          🔸 DB Backup Directory: {{ result.db_backup }}
          🔸 Disk Utilization: {{ result.disk_util }}%
          🔸 File Copied: {{ result.file_copied }}
          ------------------------------------------------------------------
          {% endfor %}
          Regards,
          DEIO Backup Automation
      run_once: true

    - name: Send consolidated DEIO Backup Summary Email
      ansible.builtin.mail:
        host: "{{ smtp_server | default('localhost') }}"
        port: "{{ smtp_port | default(25) }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from | default('deio-backup@aap.local') }}"
        subject: "DEIO Backup Summary - {{ all_backup_results[0].today_date }}"
        body: "{{ deio_email_body }}"
      delegate_to: localhost
      run_once: true
