---
- name: Email test
  hosts: all
  become: true

  tasks:
    - name: Send email
      mail:
        port: 25
        to: "mayurmk96@gmail.com"
        subject: Ansible-report
        body: System {{ ansible_hostname }} has been successfully provisioned
