---
- name: Fetch task - Download from remote servers to controller
  hosts: download_servers # Target: The servers you're pulling from
  tasks:
    - name: Fetch /etc/passwd from remote host
      ansible.builtin.fetch:
        src: /etc/passwd
        dest: /tmp/  # This is the directory on the Ansible controller where files will be placed
        flat: yes    # Important: Puts the file directly into /tmp/passwd on the controller
      register: fetch_result

    # Optional: Debug the fetch result to verify
    - name: Debug fetch result
      ansible.builtin.debug:
        var: fetch_result

    - name: Check file existence on controller
      ansible.builtin.stat:
        path: /tmp/passwd
      register: passwd_stat
      delegate_to: localhost # THIS IS KEY - runs the stat on the controller

    - name: Debug stat result
      ansible.builtin.debug:
        var: passwd_stat
      when: passwd_stat is defined      

- name: Copy task
  hosts: upload_servers
  tasks:
    - name: Copy file from local to remotw host
      ansible.builtin.copy:
        src: /tmp/passwd # Replace with the actual path on the local machine
        dest: /tmp/passwd # Replace with the desired remote path
      when: fetch_result.changed  # Only copy if the fetch was successful