---
- name: Fetch task - Download from remote servers to controller
  hosts: download_servers
  tasks:
    - name: Fetch /etc/passwd from remote host
      ansible.builtin.fetch:
        src: /etc/shadow
        dest: /mnt/host_share/  # <--- This is the path INSIDE the container that will be mapped to the host
        flat: yes
      register: fetch_result

    # You can keep your debug tasks if you wish
    - name: Debug fetch result
      ansible.builtin.debug:
        var: fetch_result

    - name: Check if /mnt/host_share/passwd exists on Ansible Controller (via volume mount)
      ansible.builtin.stat:
        path: /mnt/host_share/shadow # Check the path *inside* the container, which is mounted
      register: controller_passwd_stat
      delegate_to: localhost # This still means "the host running this task" (i.e., inside the EE)

    - name: Debug controller_passwd_stat
      ansible.builtin.debug:
        var: controller_passwd_stat

- name: Copy task - Upload from controller to remote servers
  hosts: upload_servers
  tasks:
    - name: Copy fetched file from local controller to remote host
      ansible.builtin.copy:
        src: /mnt/host_share/shadow # Source is the path inside the container, which is mounted
        dest: /tmp/shadow
      when: fetch_result.changed