---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: fetching the file from database host to controller hosts
      fetch:
        src: /home/postgres/file.csv
        dest: /var/lib/awx/projects/file_path/
        owner: awx
        group: awx
        mode: 0775
        flat: yes
