---
- name: Copy Ansible public key to target nodes
  hosts: all
  become: true

  vars:
    remote_user: ansible  # Replace if needed
    ansible_user_home: "/home/{{ remote_user }}"
    ansible_public_key_path: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa.pub' }}"

  tasks:
    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: "{{ ansible_user_home }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"

    - name: Add Ansible public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ remote_user }}"
        state: present
        key: "{{ lookup('file', ansible_public_key_path) }}"
        comment: "Ansible_key_from_{{ ansible_hostname }}"
