---
- name: Copy Ansible public key to target nodes
  hosts: all  # Or a specific group of hosts from your inventory
  become: true # Use 'become: true' if you need root/sudo privileges on the target
  vars:
    ansible_user_home: "/home/ansible" # Adjust this to the remote user's home directory
    ansible_public_key_path: "~/.ssh/id_rsa.pub" # Path to your Ansible public key on the control node

  tasks:
    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: "{{ ansible_user_home }}/.ssh"
        state: directory
        mode: '0700'
        owner: ansible # Replace with the actual remote user
        group: ansible # Replace with the actual remote user

    - name: Add Ansible public key to authorized_keys
      ansible.posix.authorized_key:
        user: your_remote_user # Replace with the actual remote user
        state: present
        key: "{{ lookup('file', ansible_public_key_path) }}"
        comment: "Ansible_key_from_{{ ansible_hostname }}" # Optional comment for the key