---
- name: Copy Ansible public key to target nodes
  hosts: all
  become: true

  vars:
    target_user: ansible
    ansible_user_home: "/home/{{ target_user }}"
    ansible_public_key_path: "{{ lookup('env', 'HOME') + '/.ssh/id_rsa.pub' }}"

  tasks:
    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: "{{ ansible_user_home }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Add Ansible public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ target_user }}"
        state: present
        key: "{{ lookup('file', ansible_public_key_path) }}"