# master_playbook.yml

# ---
# This is the master playbook that orchestrates the password expiry check.
# It runs the password_expiry_report role and then uses the mail module
# to send the generated report as an email.
# ---
- name: Run password expiry report and send email
  hosts: all
  gather_facts: false
  tasks:
    - name: Run the password expiry report role
      ansible.builtin.include_role:
        name: password_expiry_report

    - name: Find the generated report files on the control node
      find:
        paths: "./reports"
        patterns: "password_expiry_report_*.txt"
      run_once: true
      delegate_to: localhost
      register: report_files

#    - name: Send the password expiry report via email
#      mail:
#        host: "{{ smtp_server }}"
#        port: "{{ smtp_port }}"
#        from: "{{ report_sender }}"
#        to: "{{ report_recipient }}"
#        subject: "Password Expiry Report for {{ ansible_play_host_name }}"
#        body: "Attached is the password expiry report for the last run."
#        attach: "{{ item.path }}"
#      loop: "{{ report_files.files }}"
#      loop_control:
#        label: "Sending report for {{ item.path }}"
#      run_once: true
#      delegate_to: localhost