---
- name: Gather password expiry info and build single report
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - password_expiry_audit

- name: Send final master report via email
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Email the combined report
      mail:
        host: localhost
        port: 25
        subject: "Password Expiry Report - All Systems"
        from: "ansible@bank.local"
        to: "security-team@bank.local"
        attach:
          - "reports/password_expiry_master_report.txt"
        body: "Attached is the consolidated password expiry report for all systems."