- name: Invoke the Upgrade role
  hosts: all
  gather_facts: true # Explicitly ensure default gathering is on (or remove gather_facts: false if present)
  gather_timeout: 120 # Timeout in seconds for default fact gathering (e.g., 2 minutes)
  become: yes
  roles:
    - PATCHING_rhel_upgrade

  tasks:
#    - name: Build consolidated upgrade summary (gather info from all hosts)
#      ansible.builtin.set_fact:
#        consolidated_report: |
#          === RHEL Upgrade Summary Report ===
#          Generated On: {{ ansible_date_time.iso8601 }}
#          Target RHEL Version: {{ target_rhel_version | default('N/A') }}
#          
#          {% for host in ansible_play_hosts_all %}
#          Hostname: {{ host }}
#            Status: SUCCESS
#            Pre-Errata Count: {{ hostvars[host].pre_errata_count.stdout | default('N/A') }}
#            Post-Errata Count: {{ hostvars[host].post_errata_count.stdout | default('N/A') }}
#            RHEL Version Before: {{ hostvars[host].ansible_distribution_version | default('N/A') }}
#            RHEL Version After: {{ hostvars[host].post_reboot_release.stdout | default(hostvars[host].post_upgrade_release.stdout | default('N/A')) }}
#            Kernel Version: {{ hostvars[host].ansible_kernel | default('N/A') }}
#            Cluster Detected: {{ 'Yes' if hostvars[host].has_pcs_installed | default(false) else 'No' }}
#            Cluster Online Before Upgrade: {{ 'Yes' if hostvars[host].is_cluster_online | default(false) else 'No' }}
#          {% endfor %}
#    
#          --- Summary ---
#          Total Hosts: {{ ansible_play_hosts_all | length }}
#          Successful Hosts: {{ ansible_play_hosts_all | length }}  # (assumes no failures)
#          Failed Hosts: 0  # can be enhanced if you track failure stats
#    
#          --- End of Report ---
#      run_once: true
#      delegate_to: localhost
#
#    - name: Send consolidated RHEL upgrade report email
#      ansible.builtin.mail:
#        host: "{{ smtp_server }}"
#        port: "{{ smtp_port | default(25) }}"
#        to: "{{ mail_to }}"
#        from: "{{ mail_from }}"
#        subject: "Consolidated RHEL Upgrade Report - {{ ansible_date_time.date }}"
#        body: "{{ consolidated_report }}"
#      run_once: true
#      delegate_to: localhost
#      ignore_errors: true
#      tags:
#        - reporting
#



      # === Consolidated Summary and Email Reporting Section ===
    
    - name: Build consolidated upgrade summary (gather info from all hosts)
      ansible.builtin.set_fact:
        consolidated_report: |
          === RHEL Upgrade Summary Report ===
          Generated On: {{ ansible_date_time.iso8601 }}
          Target RHEL Version: {{ target_rhel_version | default('N/A') }}
          
          --- Host Details ---
          {% set success_hosts = [] %}
          {% set failed_hosts = [] %}
          {% set unreachable_hosts = [] %}
          
          {% for host in ansible_play_hosts_all %}
          {% if host in ansible_play_hosts %}
            {% set _ = success_hosts.append(host) %}
            Hostname: {{ host }}
              Status: ✅ SUCCESS
              RHEL Version Before: {{ hostvars[host].ansible_distribution_version | default('N/A') }}
              RHEL Version After: {{ hostvars[host].post_reboot_release.stdout | default(hostvars[host].post_upgrade_release.stdout | default('N/A')) }}
              Kernel Version: {{ hostvars[host].ansible_kernel | default('N/A') }}
              Pre-Errata Count: {{ hostvars[host].pre_errata_count.stdout | default('N/A') }}
              Post-Errata Count: {{ hostvars[host].post_errata_count.stdout | default('N/A') }}
              Upgrade Start: {{ hostvars[host].upgrade_start_time | default('N/A') }}
              Upgrade End: {{ hostvars[host].upgrade_end_time | default('N/A') }}
              ---
          {% else %}
            {% set _ = failed_hosts.append(host) %}
          {% endif %}
          {% endfor %}
          
          --- Summary ---
          Total Hosts: {{ ansible_play_hosts_all | length }}
          Successful Hosts: {{ success_hosts | length }}
          Failed/Unreachable Hosts: {{ failed_hosts | length }}
          
          {% if failed_hosts | length > 0 %}
          --- Failed/Unreachable Hosts ---
          {% for h in failed_hosts %}
            - {{ h }}
          {% endfor %}
          {% endif %}
          
          --- End of Report ---
      run_once: true
      delegate_to: localhost
    
#    - name: Send consolidated RHEL upgrade report email
#      ansible.builtin.mail:
#        host: "{{ smtp_server }}"
#        port: "{{ smtp_port | default(25) }}"
#        to: "{{ mail_to }}"
#        from: "{{ mail_from }}"
#        subject: "Consolidated RHEL Upgrade Report - {{ ansible_date_time.date }}"
#        body: "{{ consolidated_report }}"
#      run_once: true
#      delegate_to: localhost
#      ignore_errors: true
#      tags:
#        - reporting
