- name: Phase 1 Download CVE Bundle on Download Host
  hosts: download_servers # Targets the group containing your download host (e.g., 172.23.161.20)
  gather_facts: false # Optimize: No facts needed for this phase
  tasks:
    - name: Include download related tasks from role
      ansible.builtin.include_tasks: download_tasks.yml
      # Variables from defaults/main.yml in the role will be available here.

- name: Phase 2 Upload CVE Bundle to Upload Host
  hosts: upload_servers # Targets the group containing your upload host (e.g., 172.23.162.4)
  become: true # Enable privilege escalation for the 'core' user
  become_user: core # Execute tasks as the 'core' user on the upload host
  tasks:
    - name: Include upload related tasks from role
      ansible.builtin.include_tasks: upload_tasks.yml
      # Variables from defaults/main.yml in the role will be available here.

