---
- name: Add IP
  hosts: localhost
  vars:
    servername: "10.74.252.188"
  tasks:
    - name: Add IP
      lineinfile:
        path: /var/lib/awx/projects/rn_dummy/hosts
        line: "{{ servername  }}"
        create: yes
