---
- name: Set Fact test
  hosts: 10.74.252.188
  become: true

  tasks:
    - set_fact:
         interfaces_list: "{{ ansible_interfaces | select('match', '^(eth|wlan)[0-9]+') | list}}"
    - debug:
        msg: The interface's list on "{{ ansible_hostname }}" is "{{ interfaces_list }}"
