#SPDX-License-Identifier: MIT-0
---
# tasks file for keycopy
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_home }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Add Ansible public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    state: present
    key: "{{ lookup('file', ansible_public_key_path) }}"
