---
# tasks/04_install_agent.yml

#- name: Install Instana agent RPM
#  ansible.builtin.yum: # The 'yum' module handles .rpm files on RedHat-based systems.
#    name: "{{ instana_target_dir }}/{{ instana_rpm_file }}"
#    state: present
#  when: ansible_os_family == 'RedHat'
#  tags: [install_agent]
  # Use the yum module (or dnf, which yum module can abstract) to install the RPM on RedHat-based Linux.
  # This module is idempotent: it will only install/update if necessary.
  # If the agent is already installed with the same version, this task will report 'changed=false'.
  #

- name: Show installer file
  debug:
    msg:
      The file is "{{ instana_target_dir }}/{{ instana_rpm_file | ansible.builtin.basename }}"


- name: Install Instana agent RPM
  ansible.builtin.command: rpm -Uvh "{{ instana_target_dir }}/{{ instana_rpm_file | ansible.builtin.basename }}"
#  ansible.builtin.command: "rpm -Uvh /home/ansible/instana-agent-static-j9-*.rpm"
  when: ansible_os_family == 'RedHat'
  tags: [install_agent]

- name: Echo message after installing RPM
  ansible.builtin.debug:
    msg: "Instana Agent RPM installed successfully."
  when: ansible_os_family == 'RedHat' # Only show if it was actually installed
  tags: [install_agent]

