---
gateway_qmgr: "SFMSRBIPADGWQM"
node1_qmgr: "SFMSRBIPADCLQM1"
node2_qmgr: "SFMSRBIPADCLQM2"

node1_user: "sfmspadl301"
node2_user: "sfmspadl302"
node1_home: "/home/sfmspadl301"
node2_home: "/home/sfmspadl302"
node1_cache_home: "/sfmsapp1/sfmspdc/ehcache-clustered-3.10.8-kit/server"
node2_cache_home: "/sfmsapp2/sfmspdc/ehcache-clustered-3.10.8-kit/server"

db_sid_name: "SFMS"
oracle_home: "/orahome/app/product/19.0.0/dbhome_1"
db_unique_name: "SFMSREPK"

mq_check_matrix_n1:
  - { qmgr: "SFMSRBIPADGWQM", queue: "IDRBT.QUEUE.MANAGER" }
  - { qmgr: "SFMSRBIPADGWQM", queue: "NEFT.QPXXMITQ" }
  - { qmgr: "SFMSRBIPADGWQM", queue: "NEFT.CBSXMITQ" }
  - { qmgr: "SFMSRBIPADCLQM1", queue: "RBISPADBRQ" }
  - { qmgr: "SFMSRBIPADCLQM1", queue: "SFMS.INCOMING" }

mq_check_matrix_n2:
  - { qmgr: "SFMSRBIPADCLQM2", queue: "RBISPADBRQ" }
  - { qmgr: "SFMSRBIPADCLQM2", queue: "SFMS.INCOMING" }