---
# acs_cve_sync/tasks/main.yml

- name: Set today's date
  ansible.builtin.set_fact:
    today_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

- name: Ensure destination dir exists on download node
  ansible.builtin.file:
    path: "{{ acs_cve_dest_dir }}"
    state: directory
    mode: '0755'
    owner: ansible
    group: ansible
  delegate_to: download_host

- name: Download the CVE bundle
  ansible.builtin.get_url:
    url: "https://install.stackrox.io/scanner/scanner-vuln-updates.zip"
    dest: "{{ acs_cve_dest_dir }}/scanner-vuln-updates-{{ today_date }}.zip"
    mode: '0644'
    owner: ansible
    group: ansible
  delegate_to: download_host
  become: true
  become_user: ansible

- name: Fetch CVE zip from download host to control node
  ansible.builtin.fetch:
    src: "{{ acs_cve_dest_dir }}/scanner-vuln-updates-{{ today_date }}.zip"
    dest: "/tmp/acs-cve-files/"
    flat: true
  delegate_to: download_host
  become: false

- name: Copy CVE zip from control node to upload host
  ansible.builtin.copy:
    src: "/tmp/acs-cve-files/scanner-vuln-updates-{{ today_date }}.zip"
    dest: "{{ acs_cve_upload_dir }}/"
    mode: '0644'
  delegate_to: upload_host
  become: true
  become_user: core

- name: Set token file path (static)
  ansible.builtin.set_fact:
    rox_api_token_file: "{{ acs_cve_upload_dir }}/acs-cev-token/token.txt"

- name: Upload CVE file to ACS cluster
  ansible.builtin.command: >
    roxctl scanner upload-db
    -e {{ rox_central_address }}
    --token-file {{ rox_api_token_file }}
    --scanner-db-file {{ acs_cve_upload_dir }}/scanner-vuln-updates-{{ today_date }}.zip
  register: roxctl_upload_result
  changed_when: "'Successfully uploaded' in roxctl_upload_result.stdout"
  failed_when: roxctl_upload_result.rc != 0 or
               "'Successfully uploaded' not in roxctl_upload_result.stdout"
  delegate_to: upload_host
  become: true
  become_user: core

#- name: Cleanup CVE ZIP from control node
#  file:
#    path: "/tmp/acs-cve-files/scanner-vuln-updates-{{ today_date }}.zip"
#    state: absent
#  delegate_to: localhost