# quay_cve_sync_refined/templates/clair-config.yaml.j2
indexer:
  connstring: host=localhost port=5432 dbname=postgres user=postgres password=postgres sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
  scanner:
    repo:
      rhel-repository-scanner:
        repo2cpe_mapping_file: {{ clair_repo2cpe_mapping_file }}
    package:
      rhel_containerscanner:
        name2repos_mapping_file: {{ clair_name2repos_mapping_file }}