#- name: Clean DNF metadata
#  command: dnf clean all
#
#- name: Set release to {{ releasever }}
#  command: subscription-manager release --set {{ releasever }}
#
#- name: Show enabled repositories
#  command: subscription-manager repos --list-enabled
#  register: enabled_repos
#
#- name: Perform upgrade to RHEL {{ releasever }}
#  command: dnf --releasever={{ releasever }} --allowerasing --setopt=deltarpm=false distro-sync -y
#
#- name: Get current kernel version
#  command: uname -r
#  register: uname_out
#
#- name: Create new initramfs
#  command: "dracut -f /boot/initramfs-{{ uname_out.stdout }}.img {{ uname_out.stdout }}"
#
#- name: Run zipl
#  command: zipl
#
#- name: Reboot system
#  reboot:
#
#- name: Validate upgrade result
#  command: cat /etc/redhat-release
#  register: os_release

- name: Clean DNF metadata
  command: dnf clean all

- name: Set subscription-manager release to 8.10
  command: subscription-manager release --set 8.10

- name: Verify enabled repositories
  command: subscription-manager repos --list-enabled

- name: Perform higher-version distro-sync
  command: dnf --releasever=8.10 --allowerasing --setopt=deltarpm=false distro-sync -y

- name: Get current kernel version
  shell: uname -r
  register: current_kernel
  changed_when: false

- name: Run dracut to regenerate initramfs
  command: >
    dracut -f /boot/initramfs-{{ current_kernel.stdout }}.img {{ current_kernel.stdout }}

- name: Run zipl bootloader tool
  command: zipl

- name: Reboot the system
  reboot:
    reboot_timeout: 600

- name: Wait for system to come back
  wait_for_connection:
    timeout: 300

- name: Validate upgrade
  shell: cat /etc/redhat-release
  register: os_version_post
  changed_when: false