---
- name: Extract hostname:port from URLs (default to :443)
  set_fact:
    parsed_ssl_urls: >-
      {{
        ssl_urls
        | map('regex_replace', '^https://([^:/]+)(?::([0-9]+))?', '\\1:\\2')
        | map('regex_replace', ':$', ':443')
        | list
      }}

- name: Check SSL certificates for each host
  command: >
    openssl s_client -connect {{ item }} -servername {{ item.split(':')[0] }} -verify 5 </dev/null |
    openssl x509 -noout -dates
  loop: "{{ parsed_ssl_urls }}"
  register: cert_check_results
  failed_when: false
  changed_when: false

- name: Combine results into a dictionary
  set_fact:
    cert_info_dict: >-
      {{
        dict(
          parsed_ssl_urls | zip(
            cert_check_results.results | map(attribute='stdout') | list
          )
        )
      }}

- name: Create the SSL report
  template:
    src: report.j2
    dest: /tmp/ssl_report.txt