- name: Create SSL cert check script
  copy:
    dest: /tmp/ssl_check.sh
    mode: 0755
    content: |
      #!/bin/bash
      url=$1
      echo | openssl s_client -connect $url -servername $(echo $url | cut -d: -f1) 2>/dev/null | openssl x509 -noout -subject -issuer -dates

- name: Check SSL certificates for all URLs
  command: "/tmp/ssl_check.sh {{ item }}"
  register: cert_check_results
  loop: "{{ ssl_urls }}"
  changed_when: false
  failed_when: false

- name: Set cert facts for all URLs
  set_fact:
    cert_info_dict: >-
      {{
        dict(ssl_urls | zip(cert_check_results.results | map(attribute='stdout')))
      }}

- name: Create the SSL report
  template:
    src: report.j2
    dest: /tmp/ssl_report.txt