- name: Prepare report directory
  file:
    path: /tmp/ssl_cert_reports
    state: directory
    mode: '0755'

- name: Retrieve certificate details for each URL
  vars:
    hostname: "{{ item | regex_replace('https?://', '') | regex_replace('/.*', '') }}"
  shell: |
    echo | openssl s_client -servername {{ hostname }} -connect {{ hostname }}:443 2>/dev/null \
    | openssl x509 -noout -dates -subject -issuer -serial -fingerprint
  loop: "{{ ssl_urls }}"
  register: cert_check_results
  ignore_errors: yes
  changed_when: false

- name: Set cert facts for all URLs
  set_fact:
    certs: >-
      {{
        dict(
          cert_check_results.results
          | zip(ssl_urls)
          | map('last', 'first.stdout')
          | list
        )
      }}