---
# os_hardening_verification/tasks/check_system_updates.yml
# This file contains tasks to verify system update hardening points.

- name: Check Red Hat Satellite Server registration
  ansible.builtin.command: subscription-manager status
  register: subscription_status
  changed_when: false
  failed_when: false
  # Check the status of Red Hat Subscription Manager.
  tags:
    - system_updates
    - satellite_registration

- name: Set fact for Satellite Server registration compliance
  ansible.builtin.set_fact:
    satellite_registered_compliant: "{{ 'Current Status: Subscribed' in subscription_status.stdout }}"
  # Look for the 'Subscribed' status to confirm registration.
  tags:
    - system_updates
    - satellite_registration

- name: Define Satellite Server registration compliance item
  ansible.builtin.set_fact:
    satellite_registration_compliance_item:
      category: 'System Updates'
      item: 'Red Hat Satellite Server registration'
      status: '{{ "COMPLIANT" if satellite_registered_compliant else "NON_COMPLIANT" }}'
      expected: 'System is registered with Red Hat Satellite Server.'
      actual: '{{ "Registered" if satellite_registered_compliant else "Not Registered" }}'
      message: '{{ "System is successfully registered with Red Hat Satellite Server." if satellite_registered_compliant else "System is not registered with Red Hat Satellite Server. Output: " + subscription_status.stdout }}'
  tags:
    - system_updates
    - satellite_registration

- name: Report Red Hat Satellite Server registration compliance
  ansible.builtin.set_fact:
    compliance_report_results: "{{ compliance_report_results + [satellite_registration_compliance_item] }}"
  tags:
    - system_updates
    - satellite_registration

- name: Check Red Hat GPG key and gpgcheck enablement
  ansible.builtin.command: yum-config-manager --dump-enabled | grep gpgcheck
  register: gpgcheck_status
  changed_when: false
  failed_when: false
  # Check if gpgcheck is enabled for enabled repositories.
  tags:
    - system_updates
    - gpg_check

- name: Check for Red Hat GPG key presence
  ansible.builtin.find:
    paths: /etc/pki/rpm-gpg/
    patterns: 'RPM-GPG-KEY-redhat*'
  register: rh_gpg_key_present
  # Look for the Red Hat GPG key file.
  tags:
    - system_updates
    - gpg_check

- name: Set fact for GPG key and gpgcheck compliance
  ansible.builtin.set_fact:
    gpg_check_compliant: >-
      {{ gpgcheck_status.rc == 0 and 'gpgcheck=1' in gpgcheck_status.stdout and
         rh_gpg_key_present.matched > 0 }}
  # Both gpgcheck must be enabled and the key must be present.
  tags:
    - system_updates
    - gpg_check

- name: Define GPG key and gpgcheck compliance item
  ansible.builtin.set_fact:
    gpg_check_compliance_item:
      category: 'System Updates'
      item: 'Red Hat GPG key and gpgcheck'
      status: '{{ "COMPLIANT" if gpg_check_compliant else "NON_COMPLIANT" }}'
      expected: 'Red Hat GPG key installed and gpgcheck enabled.'
      actual: '{{ "Compliant" if gpg_check_compliant else "Non-compliant" }}'
      message: '{{ "Red Hat GPG key is installed and gpgcheck is enabled for repositories." if gpg_check_compliant else "Red Hat GPG key is missing or gpgcheck is not enabled. GPG Check Status: " + gpgcheck_status.stdout + " GPG Key Present: " + ((rh_gpg_key_present.matched > 0) | string) }}'
  tags:
    - system_updates
    - gpg_check

- name: Report GPG key and gpgcheck compliance
  ansible.builtin.set_fact:
    compliance_report_results: "{{ compliance_report_results + [gpg_check_compliance_item] }}"
  tags:
    - system_updates
    - gpg_check