- name: Ensure previous snapshot exists
  stat:
    path: "{{ system_change_output_dir }}/{{ previous_date }}"
  register: prev_dir

- name: Run diffs for each file if previous exists
  when: prev_dir.stat.exists
  block:
    - name: Run diff for {{ item }}
      command: >
        diff {{ system_change_output_dir }}/{{ previous_date }}/{{ item }}
                {{ system_change_output_dir }}/{{ timestamp }}/{{ item }}
      register: file_diff
      failed_when: false
      changed_when: false
      loop: "{{ files_to_compare }}"
      loop_control:
        loop_var: item

    - name: Save diff output
      copy:
#        content: "{{ file_diff.results[loop.index0].stdout | default('No change detected') }}"
        content: "{{ file_diff.results.stdout | default('No change detected') }}"
        dest: "{{ system_change_output_dir }}/{{ timestamp }}/diff_{{ item }}"
      loop: "{{ files_to_compare }}"
      loop_control:
        loop_var: item

- name: Create empty diff files if no previous snapshot
  when: not prev_dir.stat.exists
  copy:
    content: "No previous snapshot available for comparison."
    dest: "{{ system_change_output_dir }}/{{ timestamp }}/diff_{{ item }}"
  loop: "{{ files_to_compare }}"
  loop_control:
    loop_var: item

- name: Generate report from template
  template:
    src: system_change_report.txt.j2
    dest: "{{ system_change_output_dir }}/{{ timestamp }}/system_change_report.txt"