---
# tasks file for Quay-cve
- name: Create local directory to store CVEs
  ansible.builtin.file:
    path: "{{ local_cve_dir }}"
    state: directory
    mode: '0755'

- name: Download CVE data from source
  ansible.builtin.get_url:
    url: "{{ cve_source_url }}"
    dest: "{{ local_cve_dir }}/cve_data.json"
  register: cve_download_result

- name: Archive the CVE data
  ansible.builtin.archive:
    path: "{{ local_cve_dir }}"
    dest: "/tmp/{{ cve_archive_name }}"
    format: gz

- name: Push CVE archive to DMZ Quay node
  ansible.builtin.copy:
    src: "/tmp/{{ cve_archive_name }}"
    dest: "{{ remote_cve_dir }}/{{ cve_archive_name }}"
    mode: '0644'
    remote_src: no
  delegate_to: "{{ quay_dmz_host }}"

- name: Push CVE archive to MZ Quay node
  ansible.builtin.copy:
    src: "/tmp/{{ cve_archive_name }}"
    dest: "{{ remote_cve_dir }}/{{ cve_archive_name }}"
    mode: '0644'
    remote_src: no
  delegate_to: "{{ quay_mz_host }}"

- name: Extract CVE archive on DMZ Quay node
  ansible.builtin.unarchive:
    src: "{{ remote_cve_dir }}/{{ cve_archive_name }}"
    dest: "{{ remote_cve_dir }}"
    remote_src: yes
  delegate_to: "{{ quay_dmz_host }}"

- name: Extract CVE archive on MZ Quay node
  ansible.builtin.unarchive:
    src: "{{ remote_cve_dir }}/{{ cve_archive_name }}"
    dest: "{{ remote_cve_dir }}"
    remote_src: yes
  delegate_to: "{{ quay_mz_host }}"

- name: Trigger CVE reindexing on DMZ Quay node
  ansible.builtin.shell: "podman exec quay clairctl index --all"
  delegate_to: "{{ quay_dmz_host }}"

- name: Trigger CVE reindexing on MZ Quay node
  ansible.builtin.shell: "podman exec quay clairctl index --all"
  delegate_to: "{{ quay_mz_host }}"