- name: Check /etc/passwd permissions
  stat:
    path: /etc/passwd
  register: passwd_stat

- name: Fix /etc/passwd permissions if needed
  block:
    - name: Set permissions on /etc/passwd
      file:
        path: /etc/passwd
        owner: root
        group: root
        mode: '0644'

    - name: Log /etc/passwd fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Fixed /etc/passwd permissions'] }}"
  when: passwd_stat.stat.mode != '0644'

- name: Re-check /etc/passwd permissions
  stat:
    path: /etc/passwd
  register: passwd_stat_after

- name: Fail if /etc/passwd permissions wrong
  fail:
    msg: "/etc/passwd permissions are still incorrect"
  when: passwd_stat_after.stat.mode != '0644'
