- name: Check /tmp mount options include nodev, noexec, nosuid
  command: mount | grep '/tmp'
  register: tmp_mount
  failed_when:
    - "'nodev' not in tmp_mount.stdout"
    - "'nosuid' not in tmp_mount.stdout"
    - "'noexec' not in tmp_mount.stdout"
  vars:
    check_name: "Check /tmp mount options"
  notify: Append result to report

- name: Ensure /home is mounted with nodev
  command: mount | grep '/home'
  register: home_mount
  failed_when: "'nodev' not in home_mount.stdout"
  vars:
    check_name: "Check /home mount with nodev"
  notify: Append result to report

- name: Ensure /dev/shm has nodev, nosuid, noexec
  command: mount | grep '/dev/shm'
  register: shm_mount
  failed_when:
    - "'nodev' not in shm_mount.stdout"
    - "'nosuid' not in shm_mount.stdout"
    - "'noexec' not in shm_mount.stdout"
  vars:
    check_name: "Check /dev/shm mount options"
  notify: Append result to report

- name: Check sticky bit on world-writable dirs
  shell: find / -xdev -type d -perm -0002 ! -perm -1000
  register: sticky_dirs
  failed_when: sticky_dirs.stdout != ""
  vars:
    check_name: "Sticky bit on world-writable directories"
  notify: Append result to report