- name: Check /tmp mount options
  shell: mount | grep '/tmp'
  register: tmp_mount

- name: Fix /tmp mount options if needed
  block:
    - name: Remount /tmp with secure options
      mount:
        path: /tmp
        opts: "defaults,nodev,noexec,nosuid"
        state: mounted
    - name: Log /tmp fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Fixed /tmp mount options'] }}"
  when: >
    "'nodev' not in tmp_mount.stdout" or
    "'noexec' not in tmp_mount.stdout" or
    "'nosuid' not in tmp_mount.stdout"

- name: Re-check /tmp
  shell: mount | grep '/tmp'
  register: tmp_mount_after

- name: Fail if /tmp still non-compliant
  fail:
    msg: "/tmp is still missing required mount options"
  when: >
    "'nodev' not in tmp_mount_after.stdout" or
    "'noexec' not in tmp_mount_after.stdout" or
    "'nosuid' not in tmp_mount_after.stdout"