- name: Check if AIDE is installed
  shell: rpm -q aide
  register: aide_installed
  ignore_errors: yes

- name: Install AIDE if missing
  block:
    - name: Install AIDE package
      yum:
        name: aide
        state: present

    - name: Initialize AIDE
      command: /usr/sbin/aide --init

    - name: Log AIDE install
      set_fact:
        hardening_report: "{{ hardening_report + ['Installed and initialized AIDE'] }}"
  when: aide_installed.rc != 0

- name: Re-check AIDE installation
  shell: rpm -q aide
  register: aide_installed_after

- name: Fail if AIDE not installed
  fail:
    msg: "AIDE is not installed"
  when: aide_installed_after.rc != 0