- name: Check if firewalld is running
  shell: systemctl is-active firewalld
  register: firewalld_status
  ignore_errors: yes

- name: Start and enable firewalld if needed
  block:
    - name: Start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Log firewalld fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Started and enabled firewalld'] }}"
  when: "'active' not in firewalld_status.stdout"

- name: Re-check firewalld
  shell: systemctl is-active firewalld
  register: firewalld_status_after

- name: Fail if firewalld is not running
  fail:
    msg: "firewalld is not active"
  when: "'active' not in firewalld_status_after.stdout"
