- name: Check if IP forwarding is disabled
  shell: sysctl net.ipv4.ip_forward
  register: ip_forward
  ignore_errors: yes

- name: Disable IP forwarding if needed
  block:
    - name: Set net.ipv4.ip_forward to 0
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
        sysctl_set: yes

    - name: Log IP forwarding fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Disabled IP forwarding'] }}"
  when: "'0' not in ip_forward.stdout"

- name: Re-check IP forwarding
  shell: sysctl net.ipv4.ip_forward
  register: ip_forward_after

- name: Fail if IP forwarding is still enabled
  fail:
    msg: "IP forwarding is still enabled"
  when: "'0' not in ip_forward_after.stdout"