- name: Block new systems from network traffic during install
  debug:
    msg: "This must be enforced manually at network level in air-gapped setup."

- name: BIOS password setting notice
  debug:
    msg: "Set BIOS/firmware password manually per hardware policy."

- name: Configure boot order to prevent unauthorized boot
  debug:
    msg: "Enforce boot order in BIOS to prevent alternate boot devices."

- name: Ensure latest RHEL version
  shell: cat /etc/redhat-release
  register: os_version

- name: Print RHEL version
  debug:
    var: os_version.stdout



- name: Check if auditd service is running
  shell: systemctl is-active auditd
  register: auditd_status
  ignore_errors: yes

- name: Start and enable auditd if not running
  block:
    - name: Start and enable auditd
      systemd:
        name: auditd
        state: started
        enabled: yes

    - name: Log auditd fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Started and enabled auditd'] }}"
  when: "'active' not in auditd_status.stdout"

- name: Re-check auditd
  shell: systemctl is-active auditd
  register: auditd_status_after

- name: Fail if auditd is still inactive
  fail:
    msg: "auditd service is not active"
  when: "'active' not in auditd_status_after.stdout"
