- name: Check if Secure Boot is enabled
  shell: mokutil --sb-state
  register: sb_state
  ignore_errors: yes

- name: Fail if Secure Boot is disabled
  fail:
    msg: "Secure Boot is DISABLED. Please enable it in BIOS/UEFI."
  when: "'SecureBoot enabled' not in sb_state.stdout"

- name: Log Secure Boot check
  set_fact:
    hardening_report: "{{ hardening_report + ['Verified Secure Boot is enabled'] }}"
  when: "'SecureBoot enabled' in sb_state.stdout"