- name: Check SSH Protocol is 2
  shell: grep -E '^Protocol\s+2' /etc/ssh/sshd_config
  register: ssh_protocol
  ignore_errors: yes

- name: Fix SSH Protocol if needed
  block:
    - name: Set Protocol to 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
        backup: yes

    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted

    - name: Log SSH Protocol fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Set SSH Protocol to 2'] }}"
  when: ssh_protocol.rc != 0

- name: Re-check SSH Protocol
  shell: grep -E '^Protocol\s+2' /etc/ssh/sshd_config
  register: ssh_protocol_after

- name: Fail if SSH Protocol fix failed
  fail:
    msg: "SSH Protocol 2 fix failed"
  when: ssh_protocol_after.rc != 0