- name: Ensure Red Hat GPG key is installed
  stat:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  register: gpg_key
  failed_when: not gpg_key.stat.exists
  vars:
    check_name: "Red Hat GPG key installed"
  notify: Append result to report

- name: Ensure gpgcheck is enabled in repos
  shell: grep -r 'gpgcheck=1' /etc/yum.repos.d/
  register: gpgcheck
  ignore_errors: yes
  failed_when: gpgcheck.rc != 0
  vars:
    check_name: "Ensure gpgcheck=1 in all repos"
  notify: Append result to report