- name: Check if gpgcheck is enabled
  shell: grep -r 'gpgcheck=1' /etc/yum.repos.d/
  register: gpgcheck
  ignore_errors: yes

- name: Fix gpgcheck if needed
  block:
    - name: Enable gpgcheck in all repo files
      replace:
        path: "{{ item }}"
        regexp: 'gpgcheck=0'
        replace: 'gpgcheck=1'
      with_fileglob:
        - /etc/yum.repos.d/*.repo
    - name: Log gpgcheck fix
      set_fact:
        hardening_report: "{{ hardening_report + ['Enabled gpgcheck in repos'] }}"
  when: gpgcheck.rc != 0

- name: Re-check gpgcheck
  shell: grep -r 'gpgcheck=1' /etc/yum.repos.d/
  register: gpgcheck_after

- name: Fail if gpgcheck still disabled
  fail:
    msg: "gpgcheck is still not enforced in repos"
  when: gpgcheck_after.rc != 0