# privileged_access_audit/tasks/check_user_privileges.yml
---
- name: DEBUG - User Home Dir and SSH Path for {{ current_user }}
  ansible.builtin.debug:
    msg:
      - "Current User: {{ current_user }}"
      - "User Home Dir: {{ user_home_dirs[current_user] }}"
      - ".ssh Path to Stat: {{ user_home_dirs[current_user] }}/.ssh"
  when: current_user == 'root' # Limit debug to root for now, or remove this line to see for all users

- name: Stat .ssh directory for {{ current_user }}
  ansible.builtin.stat:
    path: "{{ user_home_dirs[current_user] }}/.ssh"
  register: ssh_dir_stat
  # Only attempt to stat if the base home directory is known and seems valid
  when:
    - user_home_dirs[current_user] is defined
    - user_home_dirs[current_user] is string
    - user_home_dirs[current_user] | length > 0
    - user_home_dirs[current_user].startswith('/')

- name: DEBUG - .ssh directory stat result for {{ current_user }}
  ansible.builtin.debug:
    var: ssh_dir_stat
  when: current_user == 'root' # Limit debug to root for now, or remove this line to see for all users

# ... rest of your check_user_privileges.yml tasks ...
# (Stat authorized_keys file, Read authorized_keys content, Add authorized_keys to report)
# Ensure these remain as per the last full copy you received.