---
# tasks file for health_check
- name: Gather system facts
  setup:

- name: Check CPU load
  shell: uptime | awk -F'load average:' '{ print $2 }' | cut -d',' -f1 | xargs
  register: cpu_load

- name: Check memory usage
  shell: free | awk '/Mem:/ { printf("%.0f", $3/$2 * 100) }'
  register: mem_usage

- name: Check disk usage
  shell: df -h / | awk 'NR==2 {print $5}' | tr -d '%'
  register: disk_usage

- name: Check I/O wait
  shell: iostat -c 1 2 | awk '/^ / {print $4}' | tail -1
  register: iowait
  ignore_errors: yes

- name: Set alert condition
  set_fact:
    alert: "{{ (cpu_load.stdout|float > cpu_load_threshold|float) or
               (mem_usage.stdout|int > memory_usage_threshold|int) or
               (disk_usage.stdout|int > disk_usage_threshold|int) or
               (iowait.stdout|default(0)|float > iowait_threshold|float) }}"

- name: Install mailx
  package:
    name: mailx
    state: present

- name: Generate report
  template:
    src: report.j2
    dest: /tmp/system_report_{{ inventory_hostname }}.txt

#- name: Send email if alert is true
#  mail:
#    to: "{{ alert_email }}"
#    subject: "System Health Alert on {{ inventory_hostname }}"
#    body: "{{ lookup('file', '/tmp/system_report_' + inventory_hostname + '.txt') }}"
#  when: alert