# ==========================================
# ODC ENVIRONMENT
# ==========================================
[odc_app_node1]
172.23.21.132

[odc_app_node2]
172.23.21.134

[odc_db_hosts]
172.23.21.164 db_role=primary
172.23.21.166 db_role=standby

# ==========================================
# DRDC ENVIRONMENT
# ==========================================
[drdc_app_node1]
172.24.21.132

[drdc_app_node2]
172.24.21.134

[drdc_db_hosts]
172.24.21.164 db_role=primary
172.24.21.166 db_role=standby

# ==========================================
# PDC ENVIRONMENT
# ==========================================
[pdc_app_node1]
172.22.21.132

[pdc_app_node2]
172.22.21.134

[pdc_db_hosts]
172.22.21.164 db_role=primary
172.22.21.166 db_role=standby

# ==========================================
# PARENT GROUPINGS
# ==========================================
[odc_app:children]
odc_app_node1
odc_app_node2

[drdc_app:children]
drdc_app_node1
drdc_app_node2

[pdc_app:children]
pdc_app_node1
pdc_app_node2

[odc:children]
odc_app
odc_db_hosts

[drdc:children]
drdc_app
drdc_db_hosts

[pdc:children]
pdc_app
pdc_db_hosts