# ==========================================
# ODC ENVIRONMENT
# ==========================================
[odc_app_node1]
172.23.21.132 ansible_host=10.28.3.40 target_qms='["SFMSRBIPADCLQM1", "SFMSRBIPADGWQM"]'

[odc_app_node2]
172.23.21.134 ansible_host=10.28.3.41 target_qms='["SFMSRBIPADCLQM2"]'

[odc_db_hosts]
172.23.21.164 db_role=primary ansible_host=10.28.4.130
172.23.21.166 db_role=standby ansible_host=10.28.6.166

# ==========================================
# DRDC ENVIRONMENT
# ==========================================
[drdc_app_node1]
172.24.21.132 ansible_host=10.35.12.66 target_qms='["SFMSRBIPADCLQM1", "SFMSRBIPADGWQM"]'

[drdc_app_node2]
172.24.21.134 ansible_host=10.35.12.67 target_qms='["SFMSRBIPADCLQM2"]'

[drdc_db_hosts]
172.24.21.164 db_role=primary ansible_host=10.35.12.68
172.24.21.166 db_role=standby ansible_host=10.35.12.69

# ==========================================
# PDC ENVIRONMENT
# ==========================================
[pdc_app_node1]
172.22.21.132 target_qms='["SFMSRBIPADCLQM1", "SFMSRBIPADGWQM"]'

[pdc_app_node2]
172.22.21.134 target_qms='["SFMSRBIPADCLQM2"]'

[pdc_db_hosts]
172.22.21.164 db_role=primary
172.22.21.166 db_role=standby

# ==========================================
# PARENT GROUPINGS
# ==========================================
[odc_app:children]
odc_app_node1
odc_app_node2

[drdc_app:children]
drdc_app_node1
drdc_app_node2

[pdc_app:children]
pdc_app_node1
pdc_app_node2

[odc:children]
odc_app
odc_db_hosts

[drdc:children]
drdc_app
drdc_db_hosts

[pdc:children]
pdc_app
pdc_db_hosts
