#SPDX-License-Identifier: MIT-0
---
# defaults file for INSTALLATION_NEW_instana_agent
---
# defaults file for INSTALLATION_Instana_Agent

instana_service_name: "instana-agent"
instana_target_dir: "/home/ansible"
instana_env_vars_script: "/etc/profile.d/instana.sh"

# --- Variables for Configuration Files ---
# Define a list of dictionaries for configuration files.
# Each dictionary should have 'path', 'filename', and 'content'.
# The 'content' will be provided by the customer at runtime or via inventory.
instana_config_files:
  - { path: "/opt/instana/agent/etc/conf.d", filename: "my_custom_config1.yaml", content: "# Content for config file 1 (to be provided by customer)" }
  - { path: "/opt/instana/agent/etc/conf.d", filename: "my_custom_config2.yaml", content: "# Content for config file 2 (to be provided by customer)" }
  - { path: "/opt/instana/agent/etc/conf.d", filename: "my_custom_config3.yaml", content: "# Content for config file 3 (to be provided by customer)" }
  - { path: "/opt/instana/agent/etc/conf.d", filename: "my_custom_config4.yaml", content: "# Content for config file 4 (to be provided by customer)" }
  - { path: "/opt/instana/agent/etc/conf.d", filename: "my_custom_config5.yaml", content: "# Content for config file 5 (to be provided by customer)" }
  - { path: "/opt/instana/agent/etc/conf.d", filename: "my_custom_config6.yaml", content: "# Content for config file 6 (to be provided by customer)" }

# --- Variables for Certificate Import ---
# Path to the certificate file on the Ansible control machine, relative to the role's 'files/' directory.
# Ensure 'instana_certificate.crt' is placed in the 'files/' directory.
instana_certificate_file_src: "instana_certificate.crt"
# Alias to use when importing the certificate into the keystore.
instana_certificate_alias: "instana_custom_cert"
# Password for the Java cacerts keystore (default is 'changeit').
# IMPORTANT: For production, use Ansible Vault to secure this variable.
instana_cacerts_password: "changeit"
# Path to the Java keystore where the certificate will be imported.
instana_cacerts_path: "/opt/instana/agent/jvm/lib/security/cacerts"
# Path to the keytool executable. Adjust if not in default PATH or if a specific JVM's keytool is needed.
instana_keytool_path: "keytool"

# --- Boolean Flags for Step Execution Control ---
# Set these to 'false' in your playbook or inventory to skip specific steps.
instana_enable_check_agent_status: true
instana_enable_copy_rpms_and_files: true
instana_enable_configure_hosts_and_env: true
instana_enable_install_agent: true
instana_enable_create_config_files: true
instana_enable_import_certificate: true
instana_enable_manage_services_post_install: true
