- name: List available kernel packages
  ansible.builtin.command:
    cmd: yum list --showduplicates kernel
  register: available_kernels
  changed_when: false


- name: Display available kernels
  ansible.builtin.debug:
    var: available_kernels.stdout_lines

- name: Construct kernel package name
  ansible.builtin.set_fact:
    kernel_package: "kernel-{{ kernel_version }}.x86_64"

- name: Validate requested kernel exists
  ansible.builtin.assert:
    that:
      - kernel_version in available_kernels.stdout
    fail_msg: >
      Requested kernel version {{ kernel_version }} is not available in enabled repositories.


- name: Debug the var 
  debug:
    var: kernel_package
  

- name: Install requested kernel
  ansible.builtin.yum:
    name: "{{ kernel_package }}"
    state: present


- name: Set kernel version for dracut
  ansible.builtin.set_fact:
    kernel_for_dracut: "{{ kernel_version }}"