---
# tasks file for patch_with_satellite
- name: Stop application services
  import_tasks: stop_services.yml

- name: Register and subscribe system to Satellite
  import_tasks: register_satellite.yml

- name: Fetch pre-patch errata count
  import_tasks: fetch_errata.yml
  vars:
    errata_phase: "pre"

- name: Apply patch and reboot
  import_tasks: patch.yml

- name: Reboot system
  import_tasks: reboot.yml

- name: Fetch post-patch errata count
  import_tasks: fetch_errata.yml
  vars:
    errata_phase: "post"

- name: Start application services
  import_tasks: start_services.yml

#- name: Send email report
#  import_tasks: send_mail.yml