- name: Patch system (included packages or all if none provided)
  ansible.builtin.yum:
    name: "{{ included_packages | default(['*']) }}"
    state: latest
    exclude: "{{ excluded_packages | default([]) }}"