- name: Check if the system is already registered
  command: subscription-manager status
  register: satellite_status
  ignore_errors: true

- name: Register the system with Satellite
  command: >
    subscription-manager register
    --org="{{ satellite_org }}"
    --activationkey="{{ satellite_activation_key }}"
    --serverurl="https://{{ satellite_server }}"
  register: reg_output
  changed_when: "'The system has been registered' in reg_output.stdout"
  when: satellite_status.rc != 0

- name: Auto-attach subscriptions
  command: subscription-manager attach --auto
  when: satellite_status.rc != 0

- name: Enable required Satellite repos
  command: subscription-manager repos --enable={{ item }}
  loop: "{{ satellite_repos }}"
  when: satellite_status.rc != 0