- name: Get hostname
  ansible.builtin.command: hostname
  register: hostname_cmd

- name: Create patch report from template
  template:
    src: patch_report.j2
    dest: /tmp/patch_report_{{ hostname_cmd.stdout }}.txt

- name: Send patch report email
  mail:
    host: "{{ smtp_host }}"
    port: 25
    to: "{{ email_recipients | join(',') }}"
    subject: "{{ mail_subject }}"
    from: "{{ mail_sender }}"
    body: "{{ lookup('file', '/tmp/patch_report.txt') }}"
