[app_nodes]
P9PDCPADAPP1 ansible_host=172.22.21.132
P9PDCPADAPP2 ansible_host=172.22.21.134

[db_nodes]
P9PDCPADDB1 ansible_host=172.22.21.164
P9PDCPADDB2 ansible_host=172.22.21.166

# Parent group grouping both clusters for full suite runs
[all_cluster_nodes:children]
app_nodes
db_nodes

