---

- name: Fetch security errata
  ansible.builtin.command: yum updateinfo list security bugfix
  register: security_errata
  changed_when: false

- name: Show security errata
  ansible.builtin.debug:
    var: security_errata.stdout_lines

- name: Fetch a post-count of errata
  ansible.builtin.shell: dnf updateinfo list available | wc -l
  register: post_errata_count
  changed_when: false
- name: Display Post-Count of Errata
  ansible.builtin.debug:
    var: post_errata_count.stdout_lines

- name: Post-Patching Checklist - End
  ansible.builtin.debug:
    msg: "Post-Patching Checklist completed."