#SPDX-License-Identifier: MIT-0
---
# tasks file for aap_cve_patch
- name: Run Pre-checks
  ansible.builtin.import_tasks: pre_checks.yml
  when: run_pre_checks

- name: Check Satellite Registration
  ansible.builtin.import_tasks: check_registration.yml
  when: enable_satellite_registration_check

- name: Check Required Repositories
  ansible.builtin.import_tasks: check_repos.yml
  when: enable_repo_check

- name: Fetch Pre-Patching Errata
  ansible.builtin.import_tasks: fetch_pre_errata.yml
  when: enable_errata_reporting

# ---- PATCHING ----

- name: Apply Security Patches
  ansible.builtin.import_tasks: apply_security.yml
  when: apply_security_patches

- name: Apply Bugfix Patches
  ansible.builtin.import_tasks: apply_bugfix.yml
  when: apply_bugfix_patches

- name: Apply Enhancement Patches
  ansible.builtin.import_tasks: apply_enhancement.yml
  when: apply_enhancement_patches

- name: Apply Kernel Patches
  ansible.builtin.import_tasks: apply_kernel.yml
  when: apply_kernel_patches

# ---- POST PATCH ----

- name: Run dracut if kernel updated
  ansible.builtin.import_tasks: dracut.yml

- name: Fetch Pre-Patching Errata
  ansible.builtin.import_tasks: fetch_ost_errata.yml
  when: enable_errata_reporting