- name: Capture basic system details
  shell: |
    echo "HOST=$(hostname)"
    echo "OS=$(cat /etc/redhat-release)"
    echo "TIME=$(date)"
  register: sysinfo
  changed_when: false

- name: Capture subscription identity (SCA safe)
  command: subscription-manager identity
  register: sub_identity
  failed_when: false
  changed_when: false

- name: Capture enabled repositories
  command: subscription-manager repos --list-enabled
  register: enabled_repos
  changed_when: false

- name: Clean and refresh metadata
  command: dnf clean all
  changed_when: false

- name: Refresh DNF cache
  command: dnf makecache
  changed_when: false

# Advisory visibility (IMPORTANT)
- name: Get full errata list
  command: dnf updateinfo list
  register: all_errata
  changed_when: false

- name: Get security errata list
  command: dnf updateinfo list security
  register: security_errata
  changed_when: false

- name: Get errata summary before patch
  command: dnf updateinfo summary
  register: errata_before
  changed_when: false