
- name: Ensure DNF/YUM plugin for updateinfo is installed (for errata reporting)
  ansible.builtin.package:
    name: "dnf-plugin-system-upgrade" # Or 'yum-plugin-security' for older RHEL/CentOS
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  # This plugin helps with 'updateinfo' command for errata details.