---
- name: Gather system architecture
  ansible.builtin.setup:
    gather_subset:
      - hardware
  
- name: Set architecture-specific RPM filename pattern
  ansible.builtin.set_fact:
    rpm_arch_pattern: "instana-agent-static-j9-*.{{ ansible_architecture }}.rpm"
  

- name: Find RPM matching architecture
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    patterns: "{{ rpm_arch_pattern }}"
  register: found_rpms
  

- name: Fail if no RPM found for architecture
  ansible.builtin.fail:
    msg: "No matching Instana agent RPM found for architecture: {{ ansible_architecture }}"
  when: found_rpms.matched == 0
  

- name: Debug - show which RPM will be copied
  ansible.builtin.debug:
    msg: "Copying RPM: {{ item.path }}"
  loop: "{{ found_rpms.files }}"
  

- name: Copy Instana agent RPM to target
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/tmp/{{ item.path | basename }}"
    mode: '0644'
  loop: "{{ found_rpms.files }}"
  
