# ==========================================
# PDC ENVIRONMENT (Primary Data Center)
# ==========================================
[pdc_app_node1]
172.22.21.132 boot_ip=172.22.21.132 cluster_ip=172.22.21.133 mounts="['/neftpadqm1','/sfmsapp1','/sfmspadgwqm','/sfmspadqm1']" target_qms='["SFMSRBIPADCLQM1", "SFMSRBIPADGWQM"]'

[pdc_app_node2]
172.22.21.134 boot_ip=172.22.21.134 cluster_ip=172.22.21.135 mounts="['/neftpadqm2','/sfmsapp2','/sfmspadqm2']" target_qms='["SFMSRBIPADCLQM2"]'

[pdc_db_hosts]
172.22.21.164 db_role=primary boot_ip=172.22.21.164 cluster_ip=172.22.21.165 mounts="['/pad_Oraarch','/pad_Oradata1','/pad_Oradata2','/pad_Oradata3','/pad_Oradata4','/pad_oraBkp']"
172.22.21.166 db_role=standby boot_ip=172.22.21.166 cluster_ip=172.22.21.167 mounts="[]"

[pdc_nodes:children]
pdc_app_node1
pdc_app_node2
pdc_db_hosts

# ==========================================
# ODC ENVIRONMENT (Onsite Data Center)
# ==========================================
[odc_app_node1]
172.23.21.132 ansible_host=10.28.3.40 boot_ip=172.23.21.132 cluster_ip=172.23.21.133 mounts="['/neftpadqm1','/sfmsapp1','/sfmspadgwqm','/sfmspadqm1']" target_qms='["SFMSRBIPADCLQM1", "SFMSRBIPADGWQM"]'

[odc_app_node2]
172.23.21.134 ansible_host=10.28.3.41 boot_ip=172.23.21.134 cluster_ip=172.23.21.135 mounts="['/neftpadqm2','/sfmsapp2','/sfmspadqm2']" target_qms='["SFMSRBIPADCLQM2"]'

[odc_db_hosts]
172.23.21.164 db_role=primary ansible_host=10.28.4.130 boot_ip=172.23.21.164 cluster_ip=172.23.21.165 mounts="['/pad_Oraarch','/pad_Oradata1','/pad_Oradata2','/pad_Oradata3','/pad_Oradata4','/pad_oraBkp']"
172.23.21.166 db_role=standby ansible_host=10.28.6.166 boot_ip=172.23.21.166 cluster_ip=172.23.21.167 mounts="[]"

[odc_nodes:children]
odc_app_node1
odc_app_node2
odc_db_hosts

# ==========================================
# DRDC ENVIRONMENT (Disaster Recovery DC)
# ==========================================
[drdc_app_node1]
172.24.21.132 ansible_host=10.35.12.66 boot_ip=172.24.21.132 cluster_ip=172.24.21.133 mounts="['/neftpadqm1','/sfmsapp1','/sfmspadgwqm','/sfmspadqm1']" target_qms='["SFMSRBIPADCLQM1", "SFMSRBIPADGWQM"]'

[drdc_app_node2]
172.24.21.134 ansible_host=10.35.12.67 boot_ip=172.24.21.134 cluster_ip=172.24.21.135 mounts="['/neftpadqm2','/sfmsapp2','/sfmspadqm2']" target_qms='["SFMSRBIPADCLQM2"]'

[drdc_db_hosts]
172.24.21.164 db_role=primary ansible_host=10.35.12.68 boot_ip=172.24.21.164 cluster_ip=172.24.21.165 mounts="['/pad_Oraarch','/pad_Oradata1','/pad_Oradata2','/pad_Oradata3','/pad_Oradata4','/pad_oraBkp']"
172.24.21.166 db_role=standby ansible_host=10.35.12.69 boot_ip=172.24.21.166 cluster_ip=172.24.21.167 mounts="[]"

[drdc_nodes:children]
drdc_app_node1
drdc_app_node2
drdc_db_hosts

# ==========================================
# GLOBAL ALL-NODES PARENT GROUP
# ==========================================
[all_nfr_nodes:children]
pdc_nodes
odc_nodes
drdc_nodes

[all_nfr_nodes:vars]
ansible_user=root
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'