[app_nodes]
# Hostname           NATTED IP for Ansible SSH          Real Boot IP on Host
P9PDCPADAPP1         ansible_host=10.100.21.132          real_ip=172.22.21.132   site=PDC
P9PDCPADAPP2         ansible_host=10.100.21.134          real_ip=172.22.21.134   site=PDC
P9ODCPADAPP1         ansible_host=10.200.21.132          real_ip=172.22.21.132   site=ODC
P9DRDCPADAPP1        ansible_host=10.300.21.132          real_ip=172.22.21.132   site=DRDC

[db_nodes]
P9PDCPADDB1          ansible_host=10.100.21.164          real_ip=172.22.21.164   site=PDC
P9PDCPADDB2          ansible_host=10.100.21.166          real_ip=172.22.21.166   site=PDC
P9ODCPADDB1          ansible_host=10.200.21.164          real_ip=172.22.21.164   site=ODC
P9DRDCPADDB1         ansible_host=10.300.21.164          real_ip=172.22.21.164   site=DRDC

[all_nfr_nodes:children]
app_nodes
db_nodes

[all_nfr_nodes:vars]
ansible_user=root
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
