---
# Main dispatcher – includes tasks based on flags
- name: Include stop service tasks
  include_tasks: stop.yml
  when: do_stop | default(false) | bool

- name: Include backup tasks
  include_tasks: backup.yml
  when: do_backup | default(false) | bool

- name: Include start service tasks
  include_tasks: start.yml
  when: do_start | default(false) | bool

# Capture action summary (for reporting)
- name: Capture DEIO backup action summary
  set_fact:
    deio_backup_result:
      hostname: "{{ inventory_hostname }}"
      actions:
        stop: "{{ do_stop | default(false) }}"
        backup: "{{ do_backup | default(false) }}"
        start: "{{ do_start | default(false) }}"
      backup_dir: "{{ today_backup_dir | default('N/A') }}"
      disk_util: "{{ archive_util.stdout | default('N/A') }}"
      system_status_before: "{{ saa_status.stdout | default('Unknown') }}"
      system_status_after: "{{ saa_status_after.stdout | default('Unknown') }}"
