---
# roles/process_audit/tasks/compare_and_report.yml

- name: Ensure controller host dir exists
  file:
    path: "{{ controller_snapshot_dir }}"
    state: directory
  delegate_to: localhost

- name: Gather all snapshots from controller dir
  find:
    paths: "{{ controller_snapshot_dir }}"
    patterns: "snapshot_*.json"
    file_type: file
  register: controller_snapshots
  delegate_to: localhost

- name: Determine current and previous snapshot paths
  set_fact:
    current_snapshot_path: "{{ controller_snapshot_dir }}/snapshot_{{ audit_date }}.json"
    previous_snapshot_path: >-
      {{ (controller_snapshots.files | map(attribute='path') | list | sort)[-2]
         if (controller_snapshots.files | length) > 1 else None }}
  delegate_to: localhost

- name: Pick previous snapshot path if exists
  set_fact:
    previous_snapshot_path: "{{ previous_snapshot_path }}"
  when: previous_snapshot_path is not none
  delegate_to: localhost

- name: Load current snapshot JSON
  set_fact:
    current_snapshot: "{{ lookup('file', current_snapshot_path) | from_json }}"
  delegate_to: localhost

- name: Load previous snapshot if available
  when: previous_snapshot_path is defined
  set_fact:
    prev_snapshot: "{{ lookup('file', previous_snapshot_path) | from_json }}"
  delegate_to: localhost

- name: Initialize prev_snapshot as empty
  when: previous_snapshot_path is not defined
  set_fact:
    prev_snapshot: {}
  delegate_to: localhost

- name: Compute diffs (processes)
  set_fact:
    process_diffs: >-
      {{ {
          'added': current_snapshot.processes | difference(prev_snapshot.processes | default([])),
          'removed': prev_snapshot.processes | default([]) | difference(current_snapshot.processes)
        } }}
  delegate_to: localhost

- name: Compute diffs (listeners/services/crons)
  set_fact:
    lsc_diffs: >-
      {{ {
          'listeners_added': current_snapshot.listeners | difference(prev_snapshot.listeners | default([])),
          'listeners_removed': prev_snapshot.listeners | default([]) | difference(current_snapshot.listeners),
          'services_added': current_snapshot.services | difference(prev_snapshot.services | default([])),
          'services_removed': prev_snapshot.services | default([]) | difference(current_snapshot.services),
          'crons_added': current_snapshot.crons | difference(prev_snapshot.crons | default([])),
          'crons_removed': prev_snapshot.crons | default([]) | difference(current_snapshot.crons)
        } }}
  delegate_to: localhost

- name: Render diff report
  template:
    src: process_audit_report.j2
    dest: "{{ controller_snapshot_dir }}/audit_report_{{ audit_date }}.txt"
  delegate_to: localhost
