---
- name: Render email text summary
  delegate_to: localhost
  template:
    src: "email_summary.txt.j2"
    dest: "{{ controller_snapshot_root }}/{{ inventory_hostname }}/email_summary_{{ ansible_date_time.iso8601_basic_short }}.txt"
    mode: "0640"
  vars:
    hostname: "{{ inventory_hostname }}"
    added_counts:
      processes: "{{ (proc_added | default([])) | length }}"
      listeners: "{{ (listen_added | default([])) | length }}"
      services: "{{ (svc_added | default([])) | length }}"
    removed_counts:
      processes: "{{ (proc_removed | default([])) | length }}"
      listeners: "{{ (listen_removed | default([])) | length }}"
      services: "{{ (svc_removed | default([])) | length }}"
    risk_counts:
      cpu: "{{ (risk_cpu | default([])) | length }}"
      mem: "{{ (risk_mem | default([])) | length }}"
      root_tmp: "{{ (risk_root_tmp | default([])) | length }}"
      ports: "{{ (risk_ports | default([])) | length }}"
      procs: "{{ (risk_procs | default([])) | length }}"
  register: email_body_file

- name: Email report via SMTP (from controller/EE)
  delegate_to: localhost
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ (smtp_username | length) > 0 | ternary(smtp_username, omit) }}"
    password: "{{ (smtp_password | length) > 0 | ternary(smtp_password, omit) }}"
    secure: "{{ smtp_use_starttls | ternary('starttls', omit) }}"
    to: "{{ mail_to | join(',') }}"
    from: "{{ mail_from }}"
    subject: "{{ mail_subject_prefix }} {{ inventory_hostname }} {{ ansible_date_time.date }}"
    body: "{{ lookup('file', email_body_file.dest) }}"
    attach:
      - "{{ host_report_path }}"
      - "{{ controller_snapshot_root }}/{{ inventory_hostname }}/process_snapshot_{{ ansible_date_time.date }}.json"
